### PR TITLE
Bugfix: Invalid code generation for literals with encoded entities like line breaks or unicode code points

### PR DESCRIPTION
**Pull request by bernd5**
Bugfix: Invalid code generation for literals with encoded entities like line breaks or unicode code points

Sample code:
```cs
Console.WriteLine($"Foo\n!")
```

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Thanks! Would you mind adding a simple test here somewhere:
https://github.com/KirillOsenkov/RoslynQuoter/blob/a89164fcdfae321d35dc92979794ec874c6bf249/src/Quoter.Tests/Tests.cs#L581

**Comment by bernd5** [comment]
Unfortenately these kind of tests do not fail because the "Token-Text" is constructed correctly - but not the "Token-ValueText". We would need to add a new kind of test which checks this.

**Comment by bernd5** [comment]
I added a test...

**Comment by KirillOsenkov** [comment]
Thanks!

**Pull request merged**
